create table PERSONA(
RUT varchar(11) primary key,
NOMBRE varchar(20),
APELLIDO varchar(20),
CORREO varchar(60),
CLAVE varchar(15),
F_NACIMIENTO date,
DIRECCION varchar(150),
TELEFONO int,
NIVEL int
)

CREATE TABLE DELIVERY(
ID_DELIVERY INT IDENTITY(1,1) PRIMARY KEY,
RUT_DELIVERY VARCHAR(11),
NOMBRE_DELIVERY VARCHAR(20),
FECHA_PEDIDO DATETIME,
Foreign key (RUT_DELIVERY) references PERSONA(RUT),
)

create table PEDIDOS(
N_PEDIDO int identity(1,1) primary key,
RUT_CLIENTE varchar(11),
FECHA_PEDIDO DATETIME,
TOTAL_PRECIO INT,
TIPO_ENTREGA INT,
ID_DELIVERY INT,
CANTIDAD INT,
ID_PRODUCTO INT,
ESTADO BIT,
Foreign key (RUT_CLIENTE) references PERSONA(RUT),
FOREIGN KEY (ID_DELIVERY) REFERENCES DELIVERY(ID_DELIVERY),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
)

create table PROVEEDORES(
RUT_PROVEEDOR VARCHAR(11) PRIMARY KEY,
NOMBRE_PROVEEDOR VARCHAR(100),
CORREO VARCHAR(50),
TELEFONO INT
)

CREATE TABLE COMPRAS(
N_COMPRA INT IDENTITY(1,1) PRIMARY KEY,
RUT_PROVEEDOR VARCHAR(11),
ID_MATERIA INT,
CANTIDAD INT,
PRECIO INT,
FECHA_COMPRA DATETIME,
FOREIGN KEY (RUT_PROVEEDOR) REFERENCES PROVEEDORES(RUT_PROVEEDOR),
FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA_PRIMA(ID_MATERIA)
)
alter table MATERIA_PRIMA
add NOMBRE_MATERIAL VARCHAR(50);
CREATE TABLE MATERIA_PRIMA(
ID_MATERIA INT IDENTITY(1,1) PRIMARY KEY,
RUT_PROVEEDOR VARCHAR(11),
CANTIDAD INT,
FECHA DATETIME,
FOREIGN KEY (RUT_PROVEEDOR) REFERENCES PROVEEDORES(RUT_PROVEEDOR)
)

CREATE TABLE PRODUCTOS(
ID_PRODUCTO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_PRODUCTO VARCHAR(30),
ID_MATERIA INT,
CATEGORIA VARCHAR(20),
STOCK INT,
COSTO INT,
PRECIO INT
FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA_PRIMA(ID_MATERIA)
)

